# Generated by Django 4.0.4 on 2022-07-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_alter_sessionyear_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
